# Script to run germline:somatic experiment P-NET on pre-formatted prostate germline and/or somatic data
# Author: Gwen Miller
# Related to the `run_pnet.py` script, which was generated by copying over and then editing everything in the file: `pnet/notebooks/prostate_metastatic_prediction_example.ipynb`

import logging
import os

import configargparse
import pandas as pd
import torch
import yaml

import wandb
from pnet import Pnet, model_selection, pnet_loader, report_and_eval

logging.basicConfig(
    encoding="utf-8",
    format="%(asctime)s %(levelname)-8s [%(name)s] %(message)s",
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S",
    force=True,
)

logger = logging.getLogger(__name__)


# adapted from https://github.com/wandb/wandb/issues/2939 to help W&B sweep
class ParseAction(configargparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        values = list(map(str, values.split()))
        setattr(namespace, self.dest, values)


def none_or_float(value):
    if value == "None" or value is None:
        return None
    return float(value)


def parse_arguments():
    parser = configargparse.ArgumentParser(description="Description of your script")
    parser.add("--config_f", type=str, required=False, is_config_file=True, help="Path to a config file")
    parser.add("--data_config_f", type=str, required=True, is_config_file=False, help="Path to a config file")
    parser.add(
        "--datasets",
        default=["somatic_amp", "somatic_del", "somatic_mut"],
        help="List of datasets to use",
        action=ParseAction,
    )  # NOTE: I don't use nargs = "+" because it doesn't work with wandb sweep
    parser.add(
        "--evaluation_set",
        default="validation",
        choices=["validation", "test"],
        help="Evaluation set (validation or test)",
    )
    parser.add("--model_type", default="bdt", choices=["bdt", "rf", "pnet"], help="Type of model")
    parser.add("--wandb_group", default="", help="Wandb group name")
    parser.add("--wandb_project", default="prostate_met_status", help="Wandb group name")
    parser.add("--seed", type=int, default=123, help="Seed value")
    parser.add("--input_data_dir", help="Directory with model-ready data")
    parser.add(
        "--data_split_dir",
        default="../../../pnet_germline/data/pnet_database/prostate/splits",
        help="Directory with data split files",
    )
    parser.add(
        "--input_data_wandb_id",
        default="",
        help="W&B run ID that created the data in the input_data_dir, if applicable",
    )
    # parser.add('--genetic_data', type=yaml.load, help="TODO: dictionary-style yaml")
    parser.add(
        "--cpus", type=int, required=False, help="Define the number of CPUs PyTorch uses during parallelization tasks"
    )
    parser.add(
        "--min_samples_split",
        type=int,
        default=2,
        help="Define the min number of samples used to make RF split (best practice usually 5-10% of dataset)",
    )
    parser.add(
        "--input_dropout", default=0.5, type=float, help="Proportion of dropout between the input layer and gene layer"
    )
    parser.add(
        "--h1_alpha",
        default=0,
        type=float,
        help="Strength of regularization on weights going to the first hidden layer (genes); default to no regularization",
    )
    parser.add(
        "--h1_regularization_method",
        default="l1",
        choices=["l1", "l2", "elasticnet"],
        help="Type of regularization on weights going to the first hidden layer (genes)",
    )
    parser.add(
        "--l1_ratio",
        required=False,
        default=0.5,
        type=float,
        help="Control the amount of L1 vs L2 regularization when using ElasticNet",
    )
    parser.add(
        "--epochs",
        type=int,
        default=500,
        help="Number of epochs to train the model (default: 500)",
    )
    return parser.parse_args()


def read_config(filename):
    with open(filename) as f:
        config = yaml.safe_load(f)
    return config


def load_input_data(config, input_dir):
    """Load genetic, confounder, and target data from disk."""
    genetic_data = {}
    for name, info in config["genetic_data"].items():
        path = os.path.join(input_dir, info["filename"])
        df = pd.read_csv(path, index_col=0)
        genetic_data[name] = df

    confounder_df = pd.read_csv(os.path.join(input_dir, config["confounder_data"]["filename"]), index_col=0)
    target_df = pd.read_csv(os.path.join(input_dir, config["target"]["filename"]), index_col=0)

    return genetic_data, confounder_df, target_df


def get_train_eval_indices(split_dir, eval_set):
    train_f = os.path.join(split_dir, "training_set.csv")
    eval_f = os.path.join(split_dir, f"{eval_set}_set.csv")

    train_ids = pd.read_csv(train_f, usecols=["id", "response"], index_col="id").index.tolist()
    eval_ids = pd.read_csv(eval_f, usecols=["id", "response"], index_col="id").index.tolist()

    return train_ids, eval_ids, train_f, eval_f


def setup_save_dir(model_type, eval_set, wandb_group, run_id, base_dir="../../results"):
    base = os.path.join(base_dir, f"{model_type}_eval_set_{eval_set}/wandbID_{run_id}")
    if wandb_group:
        base = os.path.join(base_dir, f"{wandb_group}/{model_type}_eval_set_{eval_set}/wandbID_{run_id}")
    report_and_eval.make_dir_if_needed(base)
    logger.debug(f"Save directory: {base}")
    return base


def train_model_rf(train_dataset, min_samples_split, random_seed=None):
    logger.info("Training Random Forest model")
    x_train, y_train = train_dataset.x, train_dataset.y.ravel()

    model = model_selection.run_rf(x_train, y_train, random_seed=random_seed, min_samples_split=min_samples_split)
    return model


def train_model_bdt(train_dataset, test_dataset, evaluation_set):
    logger.info("Training Gradient Boosting model")
    x_train, y_train = train_dataset.x, train_dataset.y.ravel()
    x_test, y_test = test_dataset.x, test_dataset.y.ravel()

    model = model_selection.run_bdt(x_train, y_train, random_seed=None)

    logger.info("Generating deviance plot to check convergence/overfitting")
    train_scores, test_scores = report_and_eval.get_deviance(model, x_test, y_test)
    plt = report_and_eval.get_loss_plot(
        train_losses=train_scores,
        test_losses=test_scores,
        train_label="Train deviance",
        test_label=f"{evaluation_set} deviance",
        title="Model Deviance",
        ylabel="Deviance (MSE)",
        xlabel="Boosting iterations",
    )
    wandb.log({"convergence plot": plt})
    report_and_eval.savefig(plt, os.path.join(wandb.run.dir, "deviance_per_boosting_iteration"))
    return model, train_scores, test_scores


def train_model_pnet(hparams, genetic_data, additional, y):
    logger.info("Training PNET model")
    model, train_losses, test_losses, train_dataset, test_dataset = Pnet.run(
        genetic_data,
        y,
        save_path=os.path.join(hparams["save_dir"], "model.pt"),
        additional_data=additional,
        dropout=hparams["dropout"],
        input_dropout=hparams["input_dropout"],
        lr=hparams["lr"],
        weight_decay=hparams["weight_decay"],
        batch_size=hparams["batch_size"],
        epochs=hparams["epochs"],
        verbose=hparams["verbose"],
        early_stopping=hparams["early_stopping"],
        train_inds=hparams["train_set_indices"],
        test_inds=hparams["evaluation_set_indices"],
    )

    logger.info("Logging loss curve")
    plt = report_and_eval.get_loss_plot(train_losses=train_losses, test_losses=test_losses)
    wandb.log({"convergence plot": plt})
    report_and_eval.savefig(plt, os.path.join(hparams["save_dir"], "loss_over_time"))

    return model, train_losses, test_losses, train_dataset, test_dataset


def evaluate_and_log_results(model, train_dataset, test_dataset, model_type, save_dir, eval_set_name):
    logger.info("Evaluating model on training and evaluation sets")
    report_and_eval.evaluate_interpret_save(
        model=model, pnet_dataset=train_dataset, model_type=model_type, who="train", save_dir=save_dir
    )
    report_and_eval.evaluate_interpret_save(
        model=model, pnet_dataset=test_dataset, model_type=model_type, who=eval_set_name, save_dir=save_dir
    )


def main():
    args = parse_arguments()
    wandb.login()
    run = wandb.init(project=args.wandb_project, group=args.wandb_group)
    wandb_run_id = wandb.run.id

    # Set environment
    Pnet.set_random_seeds(args.seed, turn_off_cuDNN=False)
    torch.set_num_threads(args.cpus)

    # Load config and data
    config = read_config(args.data_config_f)
    genetic_data, confounder_df, y = load_input_data(config, args.input_data_dir)
    genetic_data = {k: v for k, v in genetic_data.items() if k in args.datasets}

    # Load splits
    train_inds, eval_inds, train_f, eval_f = get_train_eval_indices(args.data_split_dir, args.evaluation_set)

    # Setup save path
    save_dir = setup_save_dir(args.model_type, args.evaluation_set, args.wandb_group, wandb_run_id)

    # Log info
    logger.info(f"Training on datasets: {list(genetic_data.keys())}")
    report_and_eval.report_df_info_with_names(genetic_data, n=5)
    report_and_eval.report_df_info_with_names({"confounders": confounder_df, "y": y}, n=5)

    # Build hparams
    hparams = {
        "wandb_run_id_that_created_inputs": args.input_data_wandb_id,
        "nbr_gene_inputs": len(genetic_data),
        "dropout": 0.2,
        "input_dropout": args.input_dropout,
        "additional_dims": confounder_df.shape[1],
        "output_dim": 1,
        "lr": 1e-3,
        "weight_decay": 1e-3,
        "epochs": args.epochs,
        "early_stopping": True,
        "batch_size": 64,
        "verbose": True,
        "train_set_indices_f": train_f,
        "evaluation_set_indices_f": eval_f,
        "train_set_indices": train_inds,
        "evaluation_set_indices": eval_inds,
        "datasets": list(genetic_data.keys()),
        "random_seed": args.seed,
        "model_type": args.model_type,
        "evaluation_set": args.evaluation_set,
        "save_dir": save_dir,
    }

    wandb.config.update(hparams)

    # Training & evaluation
    if args.model_type in ["rf", "bdt"]:
        train_dataset, test_dataset = pnet_loader.generate_train_test(
            genetic_data,
            additional_data=confounder_df,
            target=y,
            train_inds=train_inds,
            test_inds=eval_inds,
            gene_set=None,
        )
        train_dataset.input_df = pd.concat([train_dataset.input_df, train_dataset.additional_data], axis=1)
        train_dataset.x = torch.cat([train_dataset.x, train_dataset.additional], dim=1)
        test_dataset.input_df = pd.concat([test_dataset.input_df, test_dataset.additional_data], axis=1)
        test_dataset.x = torch.cat([test_dataset.x, test_dataset.additional], dim=1)

        if args.model_type == "rf":
            model = train_model_rf(train_dataset, args.min_samples_split)
        else:
            model, _, _ = train_model_bdt(train_dataset, test_dataset, args.evaluation_set)

    elif args.model_type == "pnet":
        model, _, _, train_dataset, test_dataset = train_model_pnet(hparams, genetic_data, confounder_df, y)

    evaluate_and_log_results(model, train_dataset, test_dataset, args.model_type, save_dir, args.evaluation_set)

    logger.info("Run complete. Finishing wandb.")
    wandb.finish()
    return wandb_run_id


if __name__ == "__main__":
    main()
