# Script to run germline:somatic experiment P-NET on pre-formatted prostate germline and/or somatic data
# Author: Gwen Miller
# Related to the `run_pnet.py` script, which was generated by copying over and then editing everything in the file: `pnet/notebooks/prostate_metastatic_prediction_example.ipynb`

import logging
import os

import configargparse
import pandas as pd
import torch
import yaml

import wandb
from pnet import Pnet, model_selection, pnet_loader, report_and_eval

logging.basicConfig(
    encoding="utf-8",
    format="%(asctime)s %(levelname)-8s [%(name)s] %(message)s",
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S",
    force=True,
)

logger = logging.getLogger(__name__)


# adapted from https://github.com/wandb/wandb/issues/2939 to help W&B sweep
class ParseAction(configargparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        values = list(map(str, values.split()))
        setattr(namespace, self.dest, values)


def none_or_float(value):
    if value == "None" or value is None:
        return None
    return float(value)


def parse_arguments():
    parser = configargparse.ArgumentParser(description="Description of your script")
    parser.add("--config_f", type=str, required=False, is_config_file=True, help="Path to a config file")
    parser.add("--data_config_f", type=str, required=True, is_config_file=False, help="Path to a config file")
    parser.add(
        "--datasets",
        default=["somatic_amp", "somatic_del", "somatic_mut"],
        help="List of datasets to use",
        action=ParseAction,
    )  # NOTE: I don't use nargs = "+" because it doesn't work with wandb sweep
    parser.add(
        "--evaluation_set",
        default="validation",
        choices=["validation", "test"],
        help="Evaluation set (validation or test)",
    )
    parser.add("--model_type", default="bdt", choices=["bdt", "rf", "pnet"], help="Type of model")
    parser.add("--wandb_group", default="", help="Wandb group name")
    parser.add("--wandb_project", default="prostate_met_status", help="Wandb group name")
    parser.add("--seed", type=int, default=123, help="Seed value")
    parser.add("--input_data_dir", help="Directory with model-ready data")
    parser.add(
        "--data_split_dir",
        default="../../../pnet_germline/data/pnet_database/prostate/splits",
        help="Directory with data split files",
    )
    parser.add(
        "--input_data_wandb_id",
        default="",
        help="W&B run ID that created the data in the input_data_dir, if applicable",
    )
    parser.add(
        "--cpus", type=int, required=False, help="Define the number of CPUs PyTorch uses during parallelization tasks"
    )
    parser.add(
        "--input_dropout", default=0.5, type=float, help="Proportion of dropout between the input layer and gene layer"
    )
    parser.add(
        "--h1_alpha",
        default=0,
        type=float,
        help="Strength of regularization on weights going to the first hidden layer (genes); default to no regularization",
    )
    parser.add(
        "--h1_regularization_method",
        default="l1",
        choices=["l1", "l2", "elasticnet"],
        help="Type of regularization on weights going to the first hidden layer (genes)",
    )
    parser.add(
        "--l1_ratio",
        required=False,
        default=0.5,
        type=float,
        help="Control the amount of L1 vs L2 regularization when using ElasticNet",
    )
    parser.add(
        "--epochs",
        type=int,
        default=500,
        help="Number of epochs to train the model (default: 500)",
    )
    parser.add(
        "--max_depth",
        type=int,
        default=None,
        help="Maximum depth of the tree for Random Forest (default: None, which means no limit. Use with caution as it can lead to overfitting)",
    )
    parser.add(
        "--min_samples_leaf",
        type=int,
        default=1,
        help="Minimum number of samples required to be at a leaf node for Random Forest (default: 1)",
    )
    parser.add(
        "--min_samples_split",
        type=int,
        default=50,
        help="Define the min number of samples used to make RF split (best practice usually 5-10% of dataset)",
    )
    return parser.parse_args()


def read_config(filename):
    with open(filename) as f:
        config = yaml.safe_load(f)
    return config


def load_input_data(config, input_dir):
    """Load genetic, confounder, and target data from disk."""
    genetic_data = {}
    for name, info in config["genetic_data"].items():
        path = os.path.join(input_dir, info["filename"])
        df = pd.read_csv(path, index_col=0)
        genetic_data[name] = df

    confounder_df = pd.read_csv(os.path.join(input_dir, config["confounder_data"]["filename"]), index_col=0)
    target_df = pd.read_csv(os.path.join(input_dir, config["target"]["filename"]), index_col=0)

    return genetic_data, confounder_df, target_df


def get_train_val_test_indices(
    split_dir, train_ind_f="training_set.csv", validation_ind_f="validation_set.csv", test_ind_f="test_set.csv"
):
    """
    Load train, validation, and test indices from CSV files in the specified directory.
    The CSV files should contain 'id' and 'response' columns.
    """
    train_inds = pd.read_csv(
        os.path.join(split_dir, train_ind_f), usecols=["id", "response"], index_col="id"
    ).index.tolist()
    validation_inds = pd.read_csv(
        os.path.join(split_dir, validation_ind_f), usecols=["id", "response"], index_col="id"
    ).index.tolist()
    test_inds = pd.read_csv(
        os.path.join(split_dir, test_ind_f), usecols=["id", "response"], index_col="id"
    ).index.tolist()

    return train_inds, validation_inds, test_inds


def get_train_eval_indices(split_dir, eval_set):
    train_f = os.path.join(split_dir, "training_set.csv")
    eval_f = os.path.join(split_dir, f"{eval_set}_set.csv")

    train_ids = pd.read_csv(train_f, usecols=["id", "response"], index_col="id").index.tolist()
    eval_ids = pd.read_csv(eval_f, usecols=["id", "response"], index_col="id").index.tolist()

    return train_ids, eval_ids, train_f, eval_f


def setup_save_dir(model_type, eval_set, wandb_group, run_id, base_dir="../../results"):
    base = os.path.join(base_dir, f"{model_type}_eval_set_{eval_set}/wandbID_{run_id}")
    if wandb_group:
        base = os.path.join(base_dir, f"{wandb_group}/{model_type}_eval_set_{eval_set}/wandbID_{run_id}")
    report_and_eval.make_dir_if_needed(base)
    logger.debug(f"Save directory: {base}")
    return base


def train_model_rf(train_dataset, min_samples_split=None, max_depth=None, min_samples_leaf=1, random_seed=None):
    logger.info("Training Random Forest model")
    x_train, y_train = train_dataset.x, train_dataset.y.ravel()

    model = model_selection.run_rf(
        x_train,
        y_train,
        random_seed=random_seed,
        min_samples_split=min_samples_split,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
    )
    return model


def train_model_bdt(train_dataset, test_dataset, evaluation_set):
    logger.info("Training Gradient Boosting model")
    x_train, y_train = train_dataset.x, train_dataset.y.ravel()
    x_test, y_test = test_dataset.x, test_dataset.y.ravel()

    model = model_selection.run_bdt(x_train, y_train, random_seed=None)

    logger.info("Generating deviance plot to check convergence/overfitting")
    train_scores, test_scores = report_and_eval.get_deviance(model, x_test, y_test)
    plt = report_and_eval.get_loss_plot(
        train_losses=train_scores,
        test_losses=test_scores,
        train_label="Train deviance",
        test_label=f"{evaluation_set} deviance",
        title="Model Deviance",
        ylabel="Deviance (MSE)",
        xlabel="Boosting iterations",
    )
    wandb.log({"convergence plot": plt})
    report_and_eval.savefig(plt, os.path.join(wandb.run.dir, "deviance_per_boosting_iteration"))
    return model, train_scores, test_scores


def train_model_pnet(hparams, genetic_data, additional, y):
    logger.info("Training PNET model")
    model, train_losses, test_losses, train_dataset, test_dataset = Pnet.run(
        genetic_data,
        y,
        save_path=os.path.join(hparams["save_dir"], "model.pt"),
        additional_data=additional,
        dropout=hparams["dropout"],
        input_dropout=hparams["input_dropout"],
        lr=hparams["lr"],
        weight_decay=hparams["weight_decay"],
        batch_size=hparams["batch_size"],
        epochs=hparams["epochs"],
        verbose=hparams["verbose"],
        early_stopping=hparams["early_stopping"],
        train_inds=hparams["train_set_indices"],
        test_inds=hparams["evaluation_set_indices"],
    )

    logger.info("Logging loss curve")
    plt = report_and_eval.get_loss_plot(train_losses=train_losses, test_losses=test_losses)
    wandb.log({"convergence plot": plt})
    report_and_eval.savefig(plt, os.path.join(hparams["save_dir"], "loss_over_time"))

    return model, train_losses, test_losses, train_dataset, test_dataset


def evaluate_and_log_results(model, train_dataset, test_dataset, model_type, save_dir, eval_set_name):
    logger.info("Evaluating model on training and evaluation sets")
    report_and_eval.evaluate_interpret_save(
        model=model, pnet_dataset=train_dataset, model_type=model_type, who="train", save_dir=save_dir
    )
    report_and_eval.evaluate_interpret_save(
        model=model, pnet_dataset=test_dataset, model_type=model_type, who=eval_set_name, save_dir=save_dir
    )


def evaluate_on_train_val_test(model, train_dset, val_dset, test_dset, hparams):
    """
    Evaluate a trained model on train, val, and test splits using PnetDataset.

    Args:
        model: Trained model object
        genetic_data: Input feature data (e.g., DataFrame or tensor)
        y: Target labels (Pandas Series or compatible)
        train_dset, val_dset, test_dset: PnetDataset objects for train, validation, and test sets
        hparams: Dict of hyperparameters including model_type and save_dir
    """
    for split_name, split_dset in zip(["train", "validation", "test"], [train_dset, val_dset, test_dset]):
        logger.info(f"Evaluating model on {split_name} set")

        report_and_eval.evaluate_interpret_save(
            model=model,
            pnet_dataset=split_dset,
            model_type=hparams["model_type"],
            who=split_name,
            save_dir=hparams["save_dir"],
        )
    return


def main():
    args = parse_arguments()
    wandb.login()
    run = wandb.init(project=args.wandb_project, group=args.wandb_group)
    wandb_run_id = wandb.run.id

    logger.info(f"Starting run with ID: {wandb_run_id}")
    # Set environment
    Pnet.set_random_seeds(args.seed, turn_off_cuDNN=False)
    torch.set_num_threads(args.cpus)

    # Load config and data
    config = read_config(args.data_config_f)
    genetic_data, confounder_df, y = load_input_data(config, args.input_data_dir)
    genetic_data = {k: v for k, v in genetic_data.items() if k in args.datasets}

    # Load splits
    # train_inds, eval_inds, train_f, eval_f = get_train_eval_indices(args.data_split_dir, args.evaluation_set)
    train_inds, validation_inds, test_inds = get_train_val_test_indices(args.data_split_dir)
    if args.evaluation_set == "validation":
        eval_inds = validation_inds
    elif args.evaluation_set == "test":
        eval_inds = test_inds

    # Setup save path
    save_dir = setup_save_dir(args.model_type, args.evaluation_set, args.wandb_group, wandb_run_id)

    # Log info
    logger.info(f"Training on datasets: {list(genetic_data.keys())}")
    report_and_eval.report_df_info_with_names(genetic_data, n=5)
    report_and_eval.report_df_info_with_names({"confounders": confounder_df, "y": y}, n=5)

    # Build hparams
    hparams = {
        "wandb_run_id_that_created_inputs": args.input_data_wandb_id,
        "nbr_gene_inputs": len(genetic_data),
        "dropout": 0.2,
        "input_dropout": args.input_dropout,
        "additional_dims": confounder_df.shape[1],
        "output_dim": 1,
        "lr": 1e-3,
        "weight_decay": 1e-3,
        "epochs": args.epochs,
        "early_stopping": True,
        "batch_size": 64,
        "verbose": True,
        "data_split_dir": args.data_split_dir,
        "train_set_indices": train_inds,
        "evaluation_set_indices": eval_inds,
        "test_set_indices": test_inds,
        "datasets": list(genetic_data.keys()),
        "random_seed": args.seed,
        "model_type": args.model_type,
        "evaluation_set": args.evaluation_set,
        "save_dir": save_dir,
    }
    wandb.config.update(hparams)

    # Training
    logger.info("Prepping datasets & training...")
    test_dataset = pnet_loader.generate_dataset_from_indices(
        genetic_data=genetic_data,
        target=y,
        dset_inds=test_inds,
        additional_data=confounder_df,
        gene_set=None,
        seed=args.seed,
    )
    if args.model_type in ["rf", "bdt"]:
        train_dataset, validation_dataset = pnet_loader.generate_train_test(
            genetic_data,
            additional_data=confounder_df,
            target=y,
            train_inds=train_inds,
            test_inds=eval_inds,
            gene_set=None,
        )
        # concatenate additional data to the input_df and x to match RF/BDT expectations
        train_dataset.input_df = pd.concat([train_dataset.input_df, train_dataset.additional_data], axis=1)
        train_dataset.x = torch.cat([train_dataset.x, train_dataset.additional], dim=1)
        validation_dataset.input_df = pd.concat(
            [validation_dataset.input_df, validation_dataset.additional_data], axis=1
        )
        validation_dataset.x = torch.cat([validation_dataset.x, validation_dataset.additional], dim=1)
        test_dataset.input_df = pd.concat([test_dataset.input_df, test_dataset.additional_data], axis=1)
        test_dataset.x = torch.cat([test_dataset.x, test_dataset.additional], dim=1)

        if args.model_type == "rf":
            rf_params = {
                "min_samples_leaf": args.min_samples_leaf,
                "min_samples_split": args.min_samples_split
            }
            wandb.config.update(rf_params)
            model = train_model_rf(train_dataset, min_samples_split=args.min_samples_split, max_depth=args.max_depth, min_samples_leaf=args.min_samples_leaf, random_seed=args.seed)
        else:
            model, _, _ = train_model_bdt(train_dataset, validation_dataset, args.evaluation_set)

    elif args.model_type == "pnet":
        model, _, _, train_dataset, validation_dataset = train_model_pnet(hparams, genetic_data, confounder_df, y)

    # Evaluate and log results
    logger.info("Model training complete. Evaluating model...")
    evaluate_on_train_val_test(model, train_dataset, validation_dataset, test_dataset, hparams)

    logger.info("Run complete. Finishing wandb.")
    wandb.finish()
    return wandb_run_id


if __name__ == "__main__":
    main()
