
# sweep to test impact of changing input regularization on performance, feature stability. This is a way of enforcing the biological prior that only a few genes x modalities features will actually be relevant to our task.
project: "prostate_met_status"
group: pnet_h1_regularization_001

program: run_model_on_preharmonized_data.py
method: grid
parameters:
  datasets:
    value: "somatic_amp somatic_del somatic_mut"
  data_config_f:
    value: "data.yaml"
  evaluation_set:
    values: ["validation"]
  model_type:
    values: ["pnet"]
  wandb_group:
    value: "pnet_h1_regularization_001"
  wandb_project: 
    value: "prostate_met_status"
  seed:
    values: [123]
  input_data_wandb_id:
    value: "q151d0zw"
  input_data_dir:
    value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-q151d0zw"
  cpus:
    value: 8
  h1_alpha:
    values: [0, 0.2, 0.4, 0.6, 0.8, 1.0]
  h1_regularization_method:
    values: ["l1", "l2", "elasticnet"]
  l1_ratio:
    values: [0.2, 0.4, 0.6, 0.8]

