project: "prostate_met_status"
group: pnet_perturbed_data

program: run_model_on_preharmonized_data.py
method: grid
parameters:
  datasets:
    value: "somatic_amp somatic_del somatic_mut"
  perturbed_data_dir:
    value: "../../pnet_germline/processed/perturbed_genotype_datasets/p1000_somatic_mut"
  data_config_f:
    value: "data.yaml"
  evaluation_set:
    values: ["validation"]
  model_type:
    values: ["pnet"]
  wandb_group:
    value: "pnet_perturbed_data"
  wandb_project: 
    value: "prostate_met_status"
  seed:
    values: [42]
  input_data_wandb_id:
    value: "q151d0zw"
  input_data_dir:
    value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-q151d0zw"
  cpus:
    value: 8