
# Project where the sweep runs will be logged
project: "prostate_met_status"

# sweep where all germline is combined into a single data modality
program: run_model_on_preharmonized_data.py
method: grid
parameters:
  datasets:
    values:
      - "somatic_amp somatic_del somatic_mut"
      - "germline_rare_lof"
      - "germline_rare_common_missense" # all missense
      - "germline_rare_lof_missense" # all rare
      - "germline_common_lof_missense" # all common
      - "somatic_amp somatic_del somatic_mut germline_rare_lof"
      - "germline_rare_common_lof_missense" # all 4 germline
      - "somatic_amp somatic_del somatic_mut germline_rare_common_lof_missense" # somatic and all 4 germline
      - "somatic_amp somatic_del somatic_mut germline_rare_lof_missense" # somatic and all rare
      - "somatic_amp somatic_del somatic_mut germline_common_lof_missense" # somatic and all common
      - "somatic_amp somatic_del somatic_mut germline_rare_common_lof" # somatic and all LOF
      - "somatic_amp somatic_del somatic_mut germline_rare_common_missense" # somatic and all missense
  data_config_f:
    value: "data.yaml"
  evaluation_set:
    values: ["validation"]
  model_type:
    values: ["pnet", "rf"]
  wandb_group:
    value: "pnet_somatic_and_germline_exp_004"
  wandb_project: 
    value: "prostate_met_status"
  seed:
    values: [123, 42, 155, 23, 356] 
  input_data_wandb_id:
    value: "u5yt90p1"
  input_data_dir:
    value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-u5yt90p1"
  cpus:
    value: 8
  min_samples_split:
    value: 50

# N.B.: any run that used q151d0zw as input data used germline VCFs that were filtered for quality, but did not go through the pathogenicity filters.
# program: run_model_on_preharmonized_data.py
# method: grid
# parameters:
#   datasets:
#     values:
#       - "somatic_amp somatic_del somatic_mut" # all somatic
#       - "germline_rare_common_lof_missense" # all 4 germline
#       - "somatic_amp somatic_del somatic_mut germline_rare_common_lof_missense" # all somatic and all 4 germline 
#   data_config_f:
#     value: "data.yaml"
#   evaluation_set:
#     values: ["validation"]
#   model_type:
#     values: ["pnet"]
#   wandb_group:
#     value: "pnet_somatic_and_germline_exp_003"
#   wandb_project: 
#     value: "prostate_met_status"
#   seed:
#     values: [123, 42, 155] 
#   input_data_wandb_id:
#     value: "q151d0zw"
#   input_data_dir:
#     value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-q151d0zw"
#   cpus:
#     value: 8

# # sweep to check RF hyperparameters
# program: run_model_on_preharmonized_data.py
# method: grid
# parameters:
#   datasets:
#     value: "somatic_amp somatic_del somatic_mut"
#   data_config_f:
#     value: "data.yaml"
#   evaluation_set:
#     values: ["validation"]
#   model_type:
#     values: ["rf"]
#   wandb_group: 
#     value: "pnet_somatic_and_germline_exp_003"
#   wandb_project: 
#     value: "prostate_met_status"
#   seed:
#     values: [123] 
#   input_data_wandb_id:
#     value: "q151d0zw"
#   input_data_dir:
#     value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-q151d0zw"
#   cpus:
#     value: 8
#   min_samples_split: # trying to reduce overfitting
#     values: [2, 20, 40, 50, 60, 70, 80, 90, 100, 120]

# sweep where all germline is combined into a single data modality
# program: run_model_on_preharmonized_data.py
# method: grid
# parameters:
#   datasets:
#     values:
#       - "somatic_amp somatic_del somatic_mut"
#       - "germline_rare_lof"
#       - "germline_rare_common_lof" # all LOF
#       - "germline_rare_common_missense" # all missense
#       - "germline_rare_lof_missense" # all rare
#       - "germline_common_lof_missense" # all common
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof"
#       - "germline_rare_common_lof_missense" # all 4 germline
#       - "somatic_amp somatic_del somatic_mut germline_rare_common_lof_missense" # somatic and all 4 germline
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof_missense" # somatic and all rare
#       - "somatic_amp somatic_del somatic_mut germline_common_lof_missense" # somatic and all common
#       - "somatic_amp somatic_del somatic_mut germline_rare_common_lof" # somatic and all LOF
#       - "somatic_amp somatic_del somatic_mut germline_rare_common_missense" # somatic and all missense
#   data_config_f:
#     value: "data.yaml"
#   evaluation_set:
#     values: ["validation"]
#   model_type:
#     values: ["pnet", "rf"]
#   wandb_group:
#     value: "pnet_somatic_and_germline_exp_003"
#   wandb_project: 
#     value: "prostate_met_status"
#   seed:
#     values: [123, 42, 155, 23, 356] 
#   input_data_wandb_id:
#     value: "q151d0zw"
#   input_data_dir:
#     value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-q151d0zw"
#   cpus:
#     value: 8
#   min_samples_split:
#     value: 50

# # sweep where each germline group is entered as a separate modality
# program: run_model_on_preharmonized_data.py
# method: grid
# parameters:
#   datasets:
#     values:
#       - "somatic_amp somatic_del somatic_mut"
#       - "germline_rare_lof"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof"
#       - "germline_rare_lof germline_rare_missense germline_common_lof germline_common_missense"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof germline_rare_missense germline_common_lof germline_common_missense"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof germline_rare_missense"
#       - "somatic_amp somatic_del somatic_mut germline_common_lof germline_common_missense"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof germline_common_lof"
#       - "somatic_amp somatic_del somatic_mut germline_rare_missense germline_common_missense"
#   data_config_f:
#     value: "data.yaml"
#   evaluation_set:
#     values: ["validation"]
#   model_type:
#     values: ["pnet", "rf"]
#   wandb_group:
#     value: "pnet_somatic_and_germline_exp_003"
#   seed:
#     values: [42, 155, 23, 356] 
#   input_data_wandb_id:
#     value: "33fk3jlw"
#   input_data_dir:
#     value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-33fk3jlw"
#   cpus:
#     value: 8


# program: run_model_on_preharmonized_data.py
# method: grid
# parameters:
#   datasets:
#     values:
#       - "somatic_amp somatic_del somatic_mut"
#       - "germline_rare_lof"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof"
#       - "germline_rare_lof germline_rare_missense germline_common_lof germline_common_missense"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof germline_rare_missense germline_common_lof germline_common_missense"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof germline_rare_missense"
#       - "somatic_amp somatic_del somatic_mut germline_common_lof germline_common_missense"
#       - "somatic_amp somatic_del somatic_mut germline_rare_lof germline_common_lof"
#       - "somatic_amp somatic_del somatic_mut germline_rare_missense germline_common_missense"
#   data_config_f:
#     value: "data.yaml"
#   evaluation_set:
#     values: ["validation"]
#   model_type:
#     values: ["pnet", "rf"]
#   wandb_group:
#     value: "pnet_somatic_and_germline_exp_003"
#   seed:
#     value: 123
#   input_data_wandb_id:
#     value: "33fk3jlw"
#   input_data_dir:
#     value: "../../pnet_germline/processed/wandb-group-data_prep_germline_tier12_and_somatic/converted-IDs-to-somatic_imputed-germline_True_imputed-somatic_False_paired-samples-True/wandb-run-id-33fk3jlw"
